---
minio:
  address:  
  port:  
  accessKey:
  secretKey:
  ssl:  
  bucket:
gleaner:
  runid: oih # this will be the bucket the output is placed in...
  summon: true # do we want to visit the web sites and pull down the files
  mill: false
context:
  cache: true
contextmaps:
  - prefix: "https://schema.org/"
    file: "/assets/schemaorg-current-https.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
  - prefix: "http://schema.org/"
    file: "/assets/schemaorg-current-http.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
summoner:
  after: ""      # "21 May 20 10:00 UTC"   
  mode: full  # full || diff:  If diff compare what we have currently in gleaner to sitemap, get only new, delete missing
  threads: 5
  delay:  # milliseconds (1000 = 1 second) to delay between calls (will FORCE threads to 1) 
  headless: http://workstation.lan:9222  # URL for headless see docs/headless
millers:
  graph: true
sources:
  - sourcetype: sitemap
    name: cioosatlantic
    logo: https://cioosatlantic.ca/wp-content/themes/cioos-siooc-wordpress-theme/img/atlantic/cioos-atlantic_EN.svg?x79655
    url: https://catalogue.cioosatlantic.ca/sitemap/sitemap.xml
    headless: false
    pid: ""
    propername: CIOOS Atlantic
    domain: https://cioosatlantic.ca
    active: true
    credentialsfile: ""
    other: { }
    headlesswait: 0
    delay: 0
    identifierpath: ""
    apipagelimit: 0
    identifiertype: identifiersha
    fixcontextoption: 1
    acceptcontenttype: application/ld+json, text/html
    jsonprofile: application/ld+json
  - name: euroceanexperts
    propername: EurOcean Experts
    domain: https://infohub.eurocean.net/
    catalogue: https://infohub.eurocean.net/data/experts
    logo: https://infohub.eurocean.net/images/under_constrution/eurOcean-logo-color.png
    #ODISCat entry missing ODIS-arch url & type
    pid: https://catalogue.odis.org/view/2993
    sourcetype: sitemap
    url: https://www.oceanexpert.org/assets/sitemaps/sitemapExperts.xml
    backend: Unknown
    headless: false
    dateadded: 2022-03-26
    active: true