minio:
  bucket:
  address:
  port:
  accesskey:
  secretkey:
  ssl: true
context:
    cache: true
    strict: false
contextmaps:
  - prefix: "https://schema.org/"
    file: "/assets/schemaorg-current-https.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
  - prefix: "http://schema.org/"
    file: "/assets/schemaorg-current-http.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
implementation_network:
 orgname: eco
endpoints:
  - service: ec_blazegraph
    baseurl: https://graph.geocodes-aws-dev.earthcube.org/blazegraph/namespace/test
    type: blazegraph
    authenticate: false
    username:
    password:
    modes:
      - action: sparql
        suffix: /sparql
        accept: application/sparql-results+json
        method: GET
      - action: update
        suffix: /sparql
        accept: application/sparql-update
        method: POST
      - action: bulk
        suffix: /sparql
        accept: text/x-nquads
        method: POST
objects:
  domain: us-east-1
  prefix:
    - summoned/aquadocs
    - summoned/bcodmo
    - summoned/cchdo
    - summoned/earthchem
    - summoned/edi
    - summoned/hydroshare
    - summoned/linkedearth
    - summoned/magic
    - summoned/opentopography
    - summoned/r2r
    - summoned/ssdbiodp
    - summoned/unavco
    - summoned/glim
    - summoned/gpp
    - summoned/nitrogen
    - summoned/nitrogen2
    - summoned/hydrography90m
    - summoned/neon4cast
    - summoned/usgsrc4cast
    - summoned/vera4cast
    - summoned/osmc
    - summoned/obis
    - summoned/geochemistry_custom
    - prov/aquadocs
    - prov/bcodmo
    - prov/cchdo
    - prov/earthchem
    - prov/edi
    - prov/hydroshare
    - prov/linkedearth
    - prov/magic
    - prov/opentopography
    - prov/r2r
    - prov/ssdbiodp
    - prov/unavco


