# this NEEDS
# $HOST
# $PROJECT default eco
# CONTAINER_TAG default latest


# not sure is a named external network works well with traffik, or if the label
#            - "traefik.docker.network=traefik_proxy"
# is even needed if the network is defined.

# secrets not working... these become files, so not really working
networks:
  traefik_proxy:
    driver: overlay
    name: traefik-${PROJECT:-eco}
    attachable: true
volumes:
    dagster-postgres:
        driver: local
secrets:
  MINIO_ROOT_ACCESS_KEY:
    external: true
  MINIO_ROOT_SECRET_KEY:
    external: true
services:
    dagster-dagit:
        image: docker.io/nsfearthcube/dagster-${PROJECT:-eco}:${CONTAINER_TAG:-latest}

        secrets:
          - MINIO_ROOT_ACCESS_KEY
          - MINIO_ROOT_SECRET_KEY
        environment: &env
            - DEBUG=${DEBUG:-false}
            - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
            - PORTAINER_URL=${PORTAINER_URL}
            - PORTAINER_KEY=${PORTAINER_KEY}
            - GLEANERIO_GLEANER_IMAGE=${GLEANERIO_GLEANER_IMAGE}
            - GLEANERIO_NABU_IMAGE=${GLEANERIO_NABU_IMAGE}
            - GLEANERIO_LOG_PREFIX=${GLEANERIO_LOG_PREFIX}
            - GLEANER_MINIO_ADDRESS=${GLEANERIO_MINIO_ADDRESS}
            - GLEANER_MINIO_PORT=${GLEANERIO_MINIO_PORT}
            - GLEANER_MINIO_USE_SSL=${GLEANERIO_MINIO_USE_SSL}
            - GLEANER_MINIO_BUCKET=${GLEANERIO_MINIO_BUCKET}
            - GLEANER_MINIO_ACCESS_KEY=${GLEANERIO_MINIO_ACCESS_KEY}
            - GLEANER_MINIO_SECRET_KEY=${GLEANERIO_MINIO_SECRET_KEY}
            - GLEANER_HEADLESS_ENDPOINT=${GLEANERIO_HEADLESS_ENDPOINT}
            - GLEANER_HEADLESS_NETWORK=${GLEANERIO_HEADLESS_NETWORK}
            - GLEANER_GRAPH_URL=${GLEANERIO_GRAPH_URL}
            - GLEANER_GRAPH_NAMESPACE=${GLEANERIO_GRAPH_NAMESPACE}
            - GLEANERIO_NABU_CONFIG_PATH=${GLEANERIO_NABU_CONFIG_PATH:-/configs/gleaner/nabuconfig.yaml}
            - GLEANERIO_GLEANER_CONFIG_PATH=${GLEANERIO_GLEANER_CONFIG_PATH:-/configs/gleaner/gleanerconfig.yaml}
            - GLEANERIO_NABU_DOCKER_CONFIG=${GLEANERIO_NABU_DOCKER_CONFIG:-nabu}
            - GLEANERIO_GLEANER_DOCKER_CONFIG=${GLEANERIO_GLEANER_DOCKER_CONFIG:-gleaner}
            - GLEANERIO_DATAGRAPH_ENDPOINT=${GLEANERIO_DATAGRAPH_ENDPOINT}
            - GLEANERIO_PROVGRAPH_ENDPOINT=${GLEANERIO_PROVGRAPH_ENDPOINT}
        ports:
            - 3000:3000
        networks:
          - traefik_proxy
          - dagster_host
        depends_on:
            - dagster-postgres
        labels:
              - "traefik.enable=true"
              - "traefik.http.routers.sched-${PROJECT:-eco}.entrypoints=http"
              - "traefik.http.routers.sched-${PROJECT:-eco}.priority=13"
              - "traefik.http.routers.sched-${PROJECT:-eco}.rule=Host(`sched.${HOST? HOST is required}`)"
              - "traefik.http.middlewares.sched-https-redirect.redirectscheme.scheme=https"
              - "traefik.http.routers.sched-${PROJECT:-eco}.middlewares=sched-https-redirect"
              - "traefik.http.routers.sched-${PROJECT:-eco}-secure.entrypoints=https"
              - "traefik.http.routers.sched-${PROJECT:-eco}-secure.priority=12"
              - "traefik.http.routers.sched-${PROJECT:-eco}-secure.rule=Host(`sched.${HOST? HOST is required}`)"
              - "traefik.http.routers.sched-${PROJECT:-eco}-secure.tls=true"
              - "traefik.http.routers.sched-${PROJECT:-eco}-secure.tls.certresolver=httpresolver"
              - "traefik.http.routers.sched-${PROJECT:-eco}-secure.service=sched-${PROJECT}"
              - "traefik.http.services.sched-${PROJECT:-eco}.loadbalancer.server.port=3000"
              - "traefik.docker.network=traefik_proxy"
              - "traefik.http.middlewares.sched-${PROJECT:-eco}.headers.accesscontrolallowmethods=GET,OPTIONS,POST"
              - "traefik.http.middlewares.sched-${PROJECT:-eco}.headers.accesscontrolalloworigin=*"
              - "traefik.http.middlewares.sched-${PROJECT:-eco}.headers.accesscontrolmaxage=100"
              - "traefik.http.middlewares.sched-${PROJECT:-eco}.headers.addvaryheader=true"
    dagster-daemon:
        image: docker.io/nsfearthcube/dagster-${PROJECT:-eco}:${CONTAINER_TAG:-latest}



        secrets:
          - MINIO_ROOT_ACCESS_KEY
          - MINIO_ROOT_SECRET_KEY
        environment: *env

        command: "dagster-daemon run"
        depends_on:
            - dagster-postgres
        networks:
            - dagster_host
    dagster-postgres:
        image: postgres:13.3
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=secret
        volumes:
            - dagster-postgres:/var/lib/postgresql/data
        networks:
           - traefik_proxy
    headless:
      # image: chromedp/headless-shell:stable
      # stable after 105 causes "devtool: CreateURL: Using unsafe HTTP verb GET to invoke /json/new. This action supports only PUT verb.",
      image: chromedp/headless-shell:105.0.5195.127
  #    build:
  #      context: .
  #      shm_size: "2gb"
      restart: unless-stopped
      shm_size: "2gb"
      labels:
        - "traefik.backend=headlesschrome"
        - "traefik.port=9222"
      ports:
        - 9222:9222
      environment:
        - SERVICE_PORTS=9222
      networks:
        - traefik_proxy
