version: "3.7"

services:
  docker_example_postgresql:
    image: postgres:11
    container_name: dagster-postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    networks:
      - docker_example_network

  docker_example_user_code:
    image: docker_example_user_code_image
    container_name: docker_example_user_code
    restart: always
    environment:
      DAGSTER_POSTGRES_USER: "postgres"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
      DAGSTER_CURRENT_IMAGE: "docker_example_user_code_image"
    networks:
      - docker_example_network
    env_file: ".env"

  docker_example_webserver:
    image: docker_example_webserver_image
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    container_name: docker_example_webserver
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      DAGSTER_POSTGRES_USER: "postgres"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
    volumes: # Make docker client accessible so we can terminate containers from the webserver
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - docker_example_network
    depends_on:
      - docker_example_postgresql
      - docker_example_user_code
    env_file: ".env"

  docker_example_daemon:
    image: docker_example_daemon_image
    entrypoint:
      - dagster-daemon
      - run
    container_name: docker_example_daemon
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_USER: "postgres"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
    volumes: # Make docker client accessible so we can launch containers using host docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - docker_example_network
    depends_on:
      - docker_example_postgresql
      - docker_example_user_code
    env_file: ".env"
    
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: "minio_access_key"
      MINIO_SECRET_KEY: "minio_secret_key"
    networks:
      - headless_gleanerio
      - docker_example_network

  createbuckets:
    # Creates the buckets on minio for the harvester to move assets into
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
       sleep 10;
       /usr/bin/mc alias set myminio http://minio:9000 minio_access_key minio_secret_key;
      /usr/bin/mc mb myminio/gleanerbucket;
      /usr/bin/mc anonymous set public myminio/gleanerbucket;
      sleep infinity;
       "
    networks:
      - docker_example_network
    
  createrepositories:
    # Applies migrations aka "repositories" after the database is created
    image: alpine/curl
    depends_on:
      - graphdb
    # Apply the local config files into the graphdb. We sleep 5 since even after the service is up, the graphdb is not fully ready    
    entrypoint: > 
     /bin/sh -c "
     sleep 5;
     curl -X POST http://graphdb:7200/rest/repositories -H 'Content-Type: multipart/form-data' -F 'config=@templates/iow-config.ttl'; 
     curl -X POST http://graphdb:7200/rest/repositories -H 'Content-Type: multipart/form-data' -F 'config=@templates/iowprov-config.ttl'; 
     sleep infinity"
    volumes: 
      - ./templates:/templates
    networks:
      - docker_example_network

  graphdb:
    image: khaller/graphdb-free
    container_name: graphdb
    ports:
      - 7200:7200
    environment:
      - JAVA_XMX=4g
      - JAVA_XMS=2048m
    networks:
      - headless_gleanerio
      - docker_example_network

networks:
  docker_example_network:
    external: true
  headless_gleanerio:
      external: true
