---
minio:
  address: minio
  port: 9000
  accessKey: minio_access_key
  secretKey: minio_secret_key
  ssl: false
  bucket: gleanerbucket
gleaner:
  runid: oih # this will be the bucket the output is placed in...
  summon: true # do we want to visit the web sites and pull down the files
  mill: false
context:
  cache: true
  strict: true  
contextmaps:
  - prefix: "https://schema.org/"
    file: "/assets/schemaorg-current-http.jsonld"  # wget https://schema.org/docs/jsonldcontext.jsonld
summoner:
  after: ""      # "21 May 20 10:00 UTC"   
  mode: full  # full || diff:  If diff compare what we have currently in gleaner to sitemap, get only new, delete missing
  threads: 5
  delay:  # milliseconds (1000 = 1 second) to delay between calls (will FORCE threads to 1) 
  headless: http://0.0.0.0:9222  # URL for headless see docs/headless
millers:
  graph: true
