---
minio:
  address: 127.0.0.1
  port: 9000
  accessKey: minio_access_key
  secretKey: minio_secret_key
  ssl: false
  bucket: gleaner_bucket
  region: null
implementation_network:
  orgname: iow
context:
  cache: true
  strict: true
contextmaps:
  - prefix: https://schema.org/
    file: ./assets/schemaorg-current-https.jsonld
  - prefix: http://schema.org/
    file: ./assets/schemaorg-current-http.jsonld
objects:
  domain: us-east-1
  prefix:
    - prov/counties0
    - summoned/counties0
endpoints:
  - service: iow_data
    baseurl: https://graph.geoconnex.us/repositories/iow
    type: graphdb
    authenticate: false
    username: admin
    password: jfpw
    modes:
      - action: sparql
        suffix:  # no suffix needed for GraphDB
        accept: application/sparql-results+json
        method: GET
      - action: update
        suffix: /statements
        accept: application/sparql-update
        method: POST
      - action: bulk
        suffix: /statements
        accept: text/x-nquads
        method: POST
  - service: iow_prov
    baseurl: https://graph.geoconnex.us/repositories/iowprov
    type: graphdb
    authenticate: false
    username: admin
    password: jfpw
    modes:
      - action: sparql
        suffix:  # no suffix needed for GraphDB
        accept: application/sparql-results+json
        method: GET
      - action: update
        suffix: /statements
        accept: application/sparql-update
        method: POST
      - action: bulk
        suffix: /statements
        accept: text/x-nquads
        method: POST
