---
minio:
  address: minio
  port: 9000
  accessKey: minio_access_key
  secretKey: minio_secret_key
  ssl: false
  bucket: gleanerbucket
  region: null
implementation_network:
  orgname: iow
context:
  cache: true
  strict: true
contextmaps:
  - prefix: https://schema.org/
    file: /nabu/assets/schemaorg-current-https.jsonld
  - prefix: http://schema.org/
    file: /nabu/assets/schemaorg-current-http.jsonld
objects:
  domain: us-east-1
  prefix:
    - summoned/providera
    - prov/providera
    - org
endpoints:
  - service: iow
    baseurl: http://graphdb:7200/repositories/iow
    type: graphdb
    authenticate: false
    username: admin
    password: jfpw
    modes:
      - action: sparql
        suffix:  # no suffix needed for GraphDB
        accept: application/sparql-results+json
        method: GET
      - action: update
        suffix: /statements
        accept: application/sparql-update
        method: POST
      - action: bulk
        suffix: /statements
        accept: text/x-nquads
        method: POST
  - service: iowprov
    baseurl: http://graphdb:7200/repositories/iowprov
    type: graphdb
    authenticate: false
    username: admin
    password: jfpw
    modes:
      - action: sparql
        suffix:  # no suffix needed for GraphDB
        accept: application/sparql-results+json
        method: GET
      - action: update
        suffix: /statements
        accept: application/sparql-update
        method: POST
      - action: bulk
        suffix: /statements
        accept: text/x-nquads
        method: POST
