---
minio:
  address:
  port:
  accessKey:
  secretKey:
  ssl:
  bucket:
gleaner:
  runid: oih # this will be the bucket the output is placed in...
  summon: true # do we want to visit the web sites and pull down the files
  mill: false
context:
  cache: true
contextmaps:
  - prefix: "https://schema.org/"
    file: "/assets/schemaorg-current-https.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
  - prefix: "http://schema.org/"
    file: "/assets/schemaorg-current-http.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
summoner:
  after: ""      # "21 May 20 10:00 UTC"
  mode: full  # full || diff:  If diff compare what we have currently in gleaner to sitemap, get only new, delete missing
  threads: 5
  delay:  # milliseconds (1000 = 1 second) to delay between calls (will FORCE threads to 1)
  headless: http://workstation.lan:9222  # URL for headless see docs/headless
millers:
  graph: true
sources:
  - sourcetype: sitemap
    name: acma
    propername: African Coastal and Marine Atlas catalogue (ACMA)
    catalogue: https://acma.africanmarineatlas.org
    domain: https://africanmarineatlas.org
    logo: https://acma.africanmarineatlas.org/static/mapstore/img/geonode-logo.svg
    pid: https://catalogue.odis.org/view/3125
    url: https://raw.githubusercontent.com/iodepo/odis-arch/master/collection/tempHosting/data-acma/sitemap.xml
    changefreq:
    backend: GeoNode
    headless: false
    dateadded: 2024-04-23
    cron: 0 6 * * 0
    active: true
    identifiertype: identifiersha
    identifierpath: ""
  - sourcetype: sitemap
    name: africaioc
    propername: IOC Africa Data Portal
    catalogue: https://ioc-africa.org/dbs/displayData.php
    domain: https://ioc-africa.org
    logo: https://ioc-africa.org/dbs/images/unesco_ioc_logo.png
    pid: https://oceaninfohub.org/.well-known/org/africaioc
    url: https://ioc-africa.org/sitemap.xml
    changefreq: daily
    backend: Custom
    headless: false
    dateadded: 2023-02-09
    cron: 0 6 * * 0
    active: true
    identifiertype: identifiersha
    identifierpath: ""
  - sourcetype: sitegraph
    name: aquadocs
    propername: AquaDocs
    catalogue: https://aquadocs.org/discover
    domain: https://aquadocs.org
    logo: https://aquadocs.org/themes/OR/images/repo-logo.png
    pid: https://catalogue.odis.org/view/3215
    url: https://oih.aquadocs.org/aquadocs.json
    changefreq:
    backend: OAI
    headless: false
    dateadded: 2021-02-26
    cron: 0 7 * * 0
    active: true
    identifiertype: identifiersha
    identifierpath: ""
