load_from:
#      - python_file:
#          relative_path: "project/eco/repositories/repository.py"
#          location_name: project
#          working_directory: "./project/eco/"
#      - python_file:
#          relative_path: "workflows/ecrr/repositories/repository.py"
#          working_directory: "./workflows/ecrr/"
      # module starting out with the definitions api
     # - python_module: "workflows.tasks.tasks"
      -

      - grpc_server:
            host: dagster-code-tasks
            port: 4000
            location_name: "tasks"
      - grpc_server:
            host: dagster-code-ingest
            port: 4000
            location_name: "ingest"
#      - grpc_server:
#            host: dagster-code-project
#            port: 4000
#            location_name: "project_grpc"
#      - grpc_server:
#            host: dagster-code-eco-ecrr
#            port: 4000
#            location_name: "ecrr"
