version: "3.9"

# networks: production uses traefik_proxy, buth
#  this is local testing
networks:
  traefik_proxy:
  #  driver: bridge
  headless:
    external: true
    name: ${GLEANERIO_HEADLESS_NETWORK:-headless_gleanerio}
volumes:
    dagster-postgres:
        driver: local

# let yourself use local configuration
configs:
  gleaner:
    name: ${GLEANERIO_GLEANER_DOCKER_CONFIG:-gleaner}
    file: ../configs/${PROJECT:-eco}/gleanerconfig.yaml
  nabu:
    name: ${GLEANERIO_NABU_DOCKER_CONFIG:-nabu}
    file: ../configs/${PROJECT:-eco}/nabuconfig.yaml
  workspace:
    name: ${GLEANERIO_WORKSPACE_DOCKER_CONFIG:-workspace}
    file: ../configs/${PROJECT:-eco}/workspace.yaml
# DO NOT START IN PYCHARM (unless you set the env variables in your runconfig
# USE:
# ./docker_localstart.sh
services:
    dagster-dagit:
        platform: linux/x86_64
        build:
          #context: .
          context: ..
          dockerfile: build/Dockerfile_dagster
          args:
            implnet: ${PROJECT:-eco}
        # you should be able to change the source locally, without a full rebuild.
        #image: dagster-${PROJECT:-eco}:latest
        image: dagster-local:latest
        command: 'dagster-webserver  -w ${GLEANERIO_WORKSPACE_CONFIG_PATH:-/usr/src/app/workspace.yaml}  -h "0.0.0.0" -p 3000'
        configs: &configs
          - source: workspace
            target: /usr/src/app/workspace.yaml
            # uid: "103"
            # gid: "103"
            mode:
              0444
          - source: gleaner
            target: /scheduler/gleanerconfig.yaml
            mode:
              0444
          - source: nabu
            target: /scheduler/nabuconfig.yaml
            # uid: "103"
            # gid: "103"
            mode:
              044
        volumes: &vol
          - ../deployment/dagster.yaml:/usr/src/app/dagster.yaml
          - ../generatedCode/implnet-${PROJECT:-eco}/output/:/usr/src/app/project/${PROJECT:-eco}
          - ../workflows/:/usr/src/app/workflows
        # GLEANEERIO_  the environment variables for this stack, passed into containers
        # the variables passed into the containers varies due to inconsistent standards.
        # this there are prefixed by project aka ECO_ for customization
        # DO NOT RENAME THE FIRST PART, aka the container environment variable,
        #     unless you sure what you are doing
        environment: &env
            - DEBUG=${DEBUG:-false}
            - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
            - PORTAINER_URL=${PORTAINER_URL}
            - PORTAINER_KEY=${PORTAINER_KEY}
            - GLEANERIO_GLEANER_IMAGE=${GLEANERIO_GLEANER_IMAGE}
            - GLEANERIO_NABU_IMAGE=${GLEANERIO_NABU_IMAGE}
            - GLEANERIO_LOG_PREFIX=${GLEANERIO_LOG_PREFIX}
            - GLEANERIO_SUMMARY_GRAPH_ENDPOINT=${GLEANERIO_SUMMARY_GRAPH_ENDPOINT}
            - GLEANERIO_SUMMARY_GRAPH_NAMESPACE=${GLEANERIO_SUMMARY_GRAPH_NAMESPACE}
            - GLEANERIO_MINIO_ADDRESS=${GLEANERIO_MINIO_ADDRESS}
            - GLEANERIO_MINIO_PORT=${GLEANERIO_MINIO_PORT}
            - GLEANERIO_MINIO_USE_SSL=${GLEANERIO_MINIO_USE_SSL}
            - GLEANERIO_MINIO_BUCKET=${GLEANERIO_MINIO_BUCKET}
            - GLEANERIO_MINIO_ACCESS_KEY=${GLEANERIO_MINIO_ACCESS_KEY}
            - GLEANERIO_MINIO_SECRET_KEY=${GLEANERIO_MINIO_SECRET_KEY}
            - GLEANERIO_HEADLESS_ENDPOINT=${GLEANERIO_HEADLESS_ENDPOINT}
            - GLEANERIO_HEADLESS_NETWORK=${GLEANERIO_HEADLESS_NETWORK}
            - GLEANERIO_GRAPH_URL=${GLEANERIO_GRAPH_URL}
            - GLEANERIO_GRAPH_NAMESPACE=${GLEANERIO_GRAPH_NAMESPACE}
            - GLEANERIO_NABU_CONFIG_PATH=${GLEANERIO_NABU_CONFIG_PATH:-/configs/gleaner/nabuconfig.yaml}
            - GLEANERIO_GLEANER_CONFIG_PATH=${GLEANERIO_GLEANER_CONFIG_PATH:-/configs/gleaner/gleanerconfig.yaml}
            - GLEANERIO_NABU_DOCKER_CONFIG=${GLEANERIO_NABU_DOCKER_CONFIG:-nabu}
            - GLEANERIO_GLEANER_DOCKER_CONFIG=${GLEANERIO_GLEANER_DOCKER_CONFIG:-gleaner}
            - GLEANERIO_DATAGRAPH_ENDPOINT=${GLEANERIO_DATAGRAPH_ENDPOINT}
            - GLEANERIO_PROVGRAPH_ENDPOINT=${GLEANERIO_PROVGRAPH_ENDPOINT}

        ports:
            - 3000:3000
        networks:
          - traefik_proxy
        depends_on:
            - dagster-postgres
            - dagster-code-project
            - dagster-code-tasks
        labels:
              - "traefik.enable=true"
              - "traefik.http.routers.sched.entrypoints=http"
              - "traefik.http.routers.sched.priority=13"
              - "traefik.http.routers.sched.rule=Host(`localhost`)"
              - "traefik.http.middlewares.sched-https-redirect.redirectscheme.scheme=https"
              - "traefik.http.routers.sched.middlewares=sched-https-redirect"
              - "traefik.http.routers.sched-secure.entrypoints=https"
              - "traefik.http.routers.sched-secure.priority=12"
              - "traefik.http.routers.sched-secure.rule=Host(`localhost`)"
              - "traefik.http.routers.sched-secure.tls=true"
              - "traefik.http.routers.sched-secure.tls.certresolver=httpresolver"
              - "traefik.http.routers.sched-secure.service=sched"
              - "traefik.http.services.sched.loadbalancer.server.port=3000"
              - "traefik.docker.network=traefik_proxy"
              - "traefik.http.middlewares.sched.headers.accesscontrolallowmethods=GET,OPTIONS,POST"
              - "traefik.http.middlewares.sched.headers.accesscontrolalloworigin=*"
              - "traefik.http.middlewares.sched.headers.accesscontrolmaxage=100"
              - "traefik.http.middlewares.sched.headers.addvaryheader=true"
    dagster-daemon:
        platform: linux/x86_64
        build:
          #context: .
          context: ..
          dockerfile: build/Dockerfile_dagster
          args:
            implnet: ${PROJECT:-eco}
        # you should be able to change the source locally, without a full rebuild.
       #image: dagster-${PROJECT:-eco}:latest
        image: dagster-local:latest
        configs: *configs
        environment: *env
        command: "dagster-daemon run -w ${GLEANERIO_WORKSPACE_CONFIG_PATH:-/usr/src/app/workspace.yaml}"
        volumes: *vol
        depends_on:
            - dagster-postgres
            - dagster-code-project
            - dagster-code-tasks
        networks:
            - traefik_proxy
    dagster-postgres:
        image: postgres:13.3
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=secret
        volumes:
            - dagster-postgres:/var/lib/postgresql/data
        networks:
           - traefik_proxy
    headless:
      platform: linux/x86_64
      # image: chromedp/headless-shell:stable
      # stable after 105 causes "devtool: CreateURL: Using unsafe HTTP verb GET to invoke /json/new. This action supports only PUT verb.",
      image: chromedp/headless-shell:105.0.5195.127
      #    build:
  #      context: .
  #      shm_size: "2gb"
      restart: unless-stopped
      shm_size: 265mb
      labels:
        -  "traefik.enable=false"
        - "traefik.backend=headlesschrome"
        - "traefik.port=9222"
        - "traefik.http.routers.headlesschrome-${PROJECT:-eco}.entrypoints=http"
        - "traefik.http.routers.headlesschrome-${PROJECT:-eco}.priority=13"
        - "traefik.http.routers.headlesschrome-${PROJECT:-eco}.rule=Host(`headlesschrome.${HOST? HOST is required}`)"
        - "traefik.http.middlewares.headlesschrome-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.headlesschrome-${PROJECT:-eco}.middlewares=sched-https-redirect"
        - "traefik.http.routers.headlesschrome-${PROJECT:-eco}-secure.entrypoints=https"
        - "traefik.http.routers.headlesschrome-${PROJECT:-eco}-secure.priority=12"
        - "traefik.http.routers.headlesschrome-${PROJECT:-eco}-secure.rule=Host(`headlesschrome.${HOST? HOST is required}`)"
        - "traefik.http.routers.headlesschrome-${PROJECT:-eco}-secure.tls=true"
        - "traefik.http.routers.headlesschrome-${PROJECT:-eco}-secure.tls.certresolver=httpresolver"
        - "traefik.http.routers.headlesschrome-${PROJECT:-eco}-secure.service=headlesschrome-${PROJECT}"
        - "traefik.http.services.sched-${PROJECT:-eco}.loadbalancer.server.port=9222"
        - "traefik.docker.network=traefik_proxy"
      ports:
        - 9222:9222
      environment:
        - SERVICE_PORTS=9222
        # method to get a bigger shm space, since shm_size does not work on a swarm
      tmpfs:
        - /tmp:size=256M
      volumes:
        - type: tmpfs
          target: /dev/shm

      # adding the "bridge" network does not work to give access to the 'gleaner and nabu' containers started
      # by this process. There is no name resolution on that network.
      networks:
        - traefik_proxy
        - headless
        # in code, use names defined in network above

    dagster-code-tasks:

        platform: linux/x86_64
        build:
          #context: .
          context: ..
          dockerfile: build/Dockerfile_code
          args:
            implnet: ${PROJECT:-eco}
        # you should be able to change the source locally, without a full rebuild.
       #image: dagster-${PROJECT:-eco}:latest
        image: dagster-gleanerio-local:latest

        environment: *env
        command:
        - "dagster"
        - "api"
        - "grpc"
        - "-h"
        - "0.0.0.0"
        - "-p"
        - "4000"
        - "-m"
        - "workflows.tasks.tasks"
        - "-d"
        - "/usr/src/app/"

        volumes: *vol
        depends_on:
            - dagster-postgres
        networks:
            - traefik_proxy
    dagster-code-project:

        platform: linux/x86_64
        build:
          #context: .
          context: ..
          dockerfile: build/Dockerfile_code
          args:
            implnet: ${PROJECT:-eco}
        # you should be able to change the source locally, without a full rebuild.
       #image: dagster-${PROJECT:-eco}:latest
        image: dagster-gleanerio-local:latest

        environment: *env
        command:
        - "dagster"
        - "api"
        - "grpc"
        - "-h"
        - "0.0.0.0"
        - "-p"
        - "4000"
        - "--python-file"
        - "/usr/src/app/project/${PROJECT:-eco}/repositories/repository.py"
        - "-d"
        - "/usr/src/app/project/${PROJECT:-eco}/"

        volumes: *vol
        depends_on:
            - dagster-postgres
        networks:
            - traefik_proxy
