# ###########
# This is for a single dagster instance, that does not use an externally defined network
########

# this NEEDS
# $HOST
# $PROJECT default eco
# CONTAINER_TAG default latest

networks:
  dagster_host:
  # traefik_proxy:
  #   driver: overlay
  #   name: traefik-${PROJECT:-eco}
  #   attachable: true
  #
volumes:
  dagster-postgres:
    driver: local
# secrets:
#   MINIO_ROOT_ACCESS_KEY:
#     external: true
#   MINIO_ROOT_SECRET_KEY:
#     external: true

configs:
  #  gleaner:
  #    name: ${GLEANERIO_DOCKER_GLEANER_CONFIG:-gleaner}
  #    file: ../configs/${PROJECT:-eco}/gleanerconfig.yaml
  #  nabu:
  #    name: ${GLEANERIO_DOCKER_NABU_CONFIG:-nabu}
  #    file: ../configs/${PROJECT:-eco}/nabuconfig.yaml
  workspace:
    name: ${GLEANERIO_WORKSPACE_DOCKER_CONFIG:-workspace}
    file: ../configs/${PROJECT:-eco}/workspace.yaml

services:
  dagster-dagit:
    image: earthcube/dagster_oih:0.0.2
    # image: docker.io/nsfearthcube/dagster-${PROJECT:-eco}:${CONTAINER_TAG:-latest}
    # secrets:
    #   - MINIO_ROOT_ACCESS_KEY
    #   - MINIO_ROOT_SECRET_KEY
    environment: &env
      - DEBUG=${DEBUG:-false}
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
      - PORTAINER_URL=${PORTAINER_URL}
      - PORTAINER_KEY=${PORTAINER_KEY}
      - GLEANERIO_GLEANER_IMAGE=${GLEANERIO_GLEANER_IMAGE}
      - GLEANERIO_NABU_IMAGE=${GLEANERIO_NABU_IMAGE}
      - GLEANERIO_LOG_PREFIX=${GLEANERIO_LOG_PREFIX}
      - GLEANER_MINIO_ADDRESS=${GLEANERIO_MINIO_ADDRESS}
      - GLEANER_MINIO_PORT=${GLEANERIO_MINIO_PORT}
      - GLEANER_MINIO_USE_SSL=${GLEANERIO_MINIO_USE_SSL}
      - GLEANER_MINIO_BUCKET=${GLEANERIO_MINIO_BUCKET}
      - GLEANER_MINIO_ACCESS_KEY=${GLEANERIO_MINIO_ACCESS_KEY}
      - GLEANER_MINIO_SECRET_KEY=${GLEANERIO_MINIO_SECRET_KEY}
      - GLEANER_HEADLESS_ENDPOINT=${GLEANERIO_HEADLESS_ENDPOINT}
      - GLEANER_HEADLESS_NETWORK=${GLEANERIO_HEADLESS_NETWORK}
      - GLEANER_GRAPH_URL=${GLEANERIO_GRAPH_URL}
      - GLEANER_GRAPH_NAMESPACE=${GLEANERIO_GRAPH_NAMESPACE}
      - GLEANERIO_NABU_CONFIG_PATH=${GLEANERIO_NABU_CONFIG_PATH:-/configs/gleaner/nabuconfig.yaml}
      - GLEANERIO_GLEANER_CONFIG_PATH=${GLEANERIO_GLEANER_CONFIG_PATH:-/configs/gleaner/gleanerconfig.yaml}
      - GLEANERIO_NABU_DOCKER_CONFIG=${GLEANERIO_NABU_DOCKER_CONFIG:-nabu}
      - GLEANERIO_GLEANER_DOCKER_CONFIG=${GLEANERIO_GLEANER_DOCKER_CONFIG:-gleaner}
    ports:
      - 3000:3000
    networks:
      # - traefik_proxy
      - dagster_host
    depends_on:
      - dagster-postgres

  dagster-daemon:
    image: earthcube/dagster_oih:0.0.2
    # image: docker.io/nsfearthcube/dagster-${PROJECT:-eco}:${CONTAINER_TAG:-latest}
    # secrets:
    #   - MINIO_ROOT_ACCESS_KEY
    #   - MINIO_ROOT_SECRET_KEY
    environment: *env
    command: "dagster-daemon run"
    depends_on:
      - dagster-postgres
    networks:
      - dagster_host

  dagster-postgres:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - dagster-postgres:/var/lib/postgresql/data
    networks:
      - dagster_host
        # - traefik_proxy

  headless:
    # image: chromedp/headless-shell:stable
    # stable after 105 causes "devtool: CreateURL: Using unsafe HTTP verb GET to invoke /json/new. This action supports only PUT verb.",
    image: chromedp/headless-shell:105.0.5195.127
    restart: unless-stopped
    shm_size: "2gb"
    ports:
      - 9222:9222
    environment:
      - SERVICE_PORTS=9222
    networks:
      - dagster_host
      # - traefik_proxy
