version: "3.9"

# networks: production uses traefik_proxy, buth
#  this is local testing


# DO NOT START IN PYCHARM (unless you set the env variables in your runconfig
# USE:
# ./docker_localstart.sh
services:
    dagster-dagit:
        volumes: &vol
          - ../configs/${PROJECT:-eco}/workspace.yaml:/usr/src/app/workspace.yaml
          - ../deployment/dagster.yaml:/usr/src/app/dagster.yaml
      #    - ../generatedCode/implnet-${PROJECT:-eco}/output/:/usr/src/app/project/${PROJECT:-eco}
          - ../workflows/:/usr/src/app/workflows
            # GLEANEERIO_  the environment variables for this stack, passed into containers
            # the variables passed into the containers varies due to inconsistent standards.
            # this there are prefixed by project aka ECRR_ for customization
            # DO NOT RENAME THE FIRST PART, aka the container environment variable,
            #     unless you sure what you are doing
        environment: &env
            - DEBUG_CONTAINER=${DEBUG_CONTAINER:-false}
            - GLEANERIO_CONFIG_PATH=${GLEANERIO_CONFIG_PATH:-scheduler/configs/test/}
            - GLEANERIO_DAGSTER_CONFIG_PATH=${GLEANERIO_DAGSTER_CONFIG_PATH:-scheduler/logs/}
            - GLEANERIO_DOCKER_CONTAINER_WAIT_TIMEOUT=${GLEANERIO_DOCKER_CONTAINER_WAIT_TIMEOUT:-300}
            - GLEANERIO_DOCKER_GLEANER_CONFIG=${GLEANERIO_DOCKER_GLEANER_CONFIG:-gleaner}
            - GLEANERIO_DOCKER_HEADLESS_NETWORK=${GLEANERIO_DOCKER_HEADLESS_NETWORK}
            - GLEANERIO_DOCKER_NABU_CONFIG=${GLEANERIO_DOCKER_NABU_CONFIG:-nabu}
            - GLEANERIO_DOCKER_URL=${GLEANERIO_DOCKER_URL}
            - GLEANERIO_DOCKER_WORKSPACE_CONFIG=${GLEANERIO_DOCKER_WORKSPACE_CONFIG}
            - GLEANERIO_GLEANER_CONFIG_PATH=${GLEANERIO_GLEANER_CONFIG_PATH:-/configs/gleaner/gleanerconfig.yaml}
            - GLEANERIO_GLEANER_IMAGE=${GLEANERIO_GLEANER_IMAGE}
            - GLEANERIO_GRAPH_NAMESPACE=${GLEANERIO_GRAPH_NAMESPACE}
            - GLEANERIO_GRAPH_SUMMARIZE=${GLEANERIO_GRAPH_SUMMARIZE:-false}
            - GLEANERIO_GRAPH_SUMMARY_ENDPOINT=${GLEANERIO_GRAPH_SUMMARY_ENDPOINT:-${GLEANERIO_GRAPH_URL}}
            - GLEANERIO_GRAPH_SUMMARY_NAMESPACE=${GLEANERIO_GRAPH_SUMMARY_NAMESPACE}
            - GLEANERIO_GRAPH_URL=${GLEANERIO_GRAPH_URL}
            - GLEANERIO_HEADLESS_ENDPOINT=${GLEANERIO_HEADLESS_ENDPOINT}
            - GLEANERIO_LOG_PREFIX=${GLEANERIO_LOG_PREFIX:-scheduler/logs/}
            - GLEANERIO_MINIO_ACCESS_KEY=${GLEANERIO_MINIO_ACCESS_KEY}
            - GLEANERIO_MINIO_ADDRESS=${GLEANERIO_MINIO_ADDRESS}
            - GLEANERIO_MINIO_BUCKET=${GLEANERIO_MINIO_BUCKET}
            - GLEANERIO_MINIO_PORT=${GLEANERIO_MINIO_PORT}
            - GLEANERIO_MINIO_SECRET_KEY=${GLEANERIO_MINIO_SECRET_KEY}
            - GLEANERIO_MINIO_USE_SSL=${GLEANERIO_MINIO_USE_SSL}
            - GLEANERIO_NABU_CONFIG_PATH=${GLEANERIO_NABU_CONFIG_PATH:-/configs/gleaner/nabuconfig.yaml}
            - GLEANERIO_NABU_IMAGE=${GLEANERIO_NABU_IMAGE}
            - GLEANERIO_PORTAINER_APIKEY=${GLEANERIO_PORTAINER_APIKEY}
            - GLEANERIO_DEFAULT_SCHEDULE=${GLEANERIO_DEFAULT_SCHEDULE:-@weekly}
            - GLEANERIO_DEFAULT_SCHEDULE_TIMEZONE=${GLEANERIO_DEFAULT_SCHEDULE_TIMEZONE:-"America/Los_Angeles"}
            - GLEANERIO_SOURCES_FILENAME=${GLEANERIO_SOURCES_FILENAME:-gleanerconfig.yaml}
            - GLEANERIO_TENANT_FILENAME=${GLEANERIO_TENANT_FILENAME:-tenant.yaml}
            - GLEANERIO_WORKSPACE_CONFIG_PATH=${GLEANERIO_WORKSPACE_CONFIG_PATH}
            - GLEANERIO_CSV_CONFIG_URL=${GLEANERIO_CSV_CONFIG_URL:-https://docs.google.com/spreadsheets/d/e/2PACX-1vTt_45dYd5LMFK9Qm_lCg6P7YxG-ae0GZEtrHMZmNbI-y5tVDd8ZLqnEeIAa-SVTSztejfZeN6xmRZF/pub?gid=1340502269&single=true&output=csv}
            - ECRR_MINIO_BUCKET=${ECRR_MINIO_BUCKET}
            - ECRR_GRAPH_NAMESPACE=${ECRR_GRAPH_NAMESPACE}
            - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
            - SLACK_CHANNEL=${SLACK_CHANNEL:-"#twitterfeed"}
            - SLACK_TOKEN=${SLACK_TOKEN}
# caution for a portainer additional file deply
    # portainer issue, merging commands may need to create a combined customised on
        command: 'dagster-webserver  -w workspace.yaml  -h "0.0.0.0" -p 3000'
        depends_on: &deps
            - dagster-postgres
            -   dagster-code-ingest
            - dagster-code-tasks
            - dagster-code-eco-ecrr

    dagster-daemon:
# caution for a portainer additional file deply
    # portainer issue, merging commands may need to create a combined customised on
        command: "dagster-daemon run -w workspace.yaml  "
        depends_on: *deps

## GRPC servers are not just serving the code
# they need to compile it, so same image for all dagster-*
    dagster-code-eco-ecrr:

        platform: linux/x86_64
        build:
          #context: .
          context: ..
          dockerfile: build/Dockerfile_code
          args:
            implnet: ${PROJECT:-eco}
        # you should be able to change the source locally, without a full rebuild.
       #image: dagster-${PROJECT:-eco}:latest
        image: dagster-gleanerio-local:latest

        environment: *env
        command:
        - "dagster"
        - "api"
        - "grpc"
        - "-h"
        - "0.0.0.0"
        - "-p"
        - "4000"
        - "-m"
        - "workflows.ecrr.ecrr"
        - "-d"
        - "/usr/src/app/"

        volumes: *vol
        depends_on:
            - dagster-postgres
        networks:
            - traefik_proxy

