services:
  dagster-dagit:
    image: docker.io/fils/dagster:0.0.1
    environment:
    - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    ports:
      - 3000:3000
  dagster-daemon:
    image: docker.io/fils/dagster:0.0.1
    environment:
    - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    command: "dagster-daemon run"
  dagster-postgres:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - dagster-postgres:/var/lib/postgresql/data
volumes:
  dagster-postgres:
    driver: local
