minio:
    address:
    port: 443
    ssl: true
    bucket: ecrr
    region: ""
    accesskey:
    secretkey:
objects:
    bucket: ecrr
    domain: us-east-1
    prefix:
        - summoned/ecrr_submitted
        - summoned/geocodes_examples
        - org
    prefixoff:
        - summoned/ecrr_examples
implementation_network:
 orgname: ecrr
endpoints:
  - service: ec_blazegraph
    baseurl:  http://localhost/blazegraph/namespace/earthcube/sparql
    type: blazegraph
    authenticate: false
    username:
    password:
    modes:
      - action: sparql
        suffix: /sparql
        accept: application/sparql-results+json
        method: GET
      - action: update
        suffix: /sparql
        accept: application/sparql-update
        method: POST
      - action: bulk
        suffix: /sparql
        accept: text/x-nquads
        method: POST
txtaipkg:
    endpoint: http://0.0.0.0:8000
