API Flow: {
  shape: sequence_diagram
  dag: Dagster
  prt: Portainer
  s3: Minio
  Create: {
    dag -> prt: containers/create
    prt -> dag: 200
  }
  Archive: {
    dag -> s3 : request archive (configs)
    s3 -> dag: 200
    dag -> prt: containers/CID/archive
    prt -> dag: 200
  }
  Start: {
    dag -> prt: containers/CID/start
    prt -> dag: 200
  }
  Wait: {
    dag -> prt: containers/CID/wait
    prt -> dag: 200
  }
  Copy: {
    dag -> prt: containers/CID/logs
    prt -> dag: 200
    dag -> s3 : copy up logs
    s3 -> dag: 200
  }
  Remove: {
    dag -> prt: containers/CID
    prt -> dag: 204
  }



}
