direction: right

s : Community maintained \n sources
gc: Gleaner Cfg
assets: Supporting asset files \n contexts, etc.

dag: Dagster
dag.dc: Dagster Code
dag.di: Dagster Images \n (dagster, dagit, postgres)
ar: Archive

port: Portainer (Docker)

gio: GleanerIO
gio.Nabu
gio.Gleaner
gio.images: Gleaner Images \n (gleaner, nabu)

gio.Nabu -> gio.images
gio.Gleaner -> gio.images


garch: Gleaner Arch Images \n (headless, s3, graphdb)
garch.s3
garch.triplestore
garch.headless: headless chrome

s -> gc: Cfg builder
gc -> ar
assets -> ar
gc -> dag.dc: generator.sh
dag.dc -> dag.di: Docker build
dag.di -> port: Docker compose
ar -> garch.s3
garch.s3 <- port: Docker archive api via Dagster
gio.images <- port: Docker API via Dagster
garch -> port: Docker compose
