Object Flow: {
  
  shape: sequence_diagram
  p:  Provider
  g:  Glaner
  n:  Nabu
  os: Object Store
  ts: Triple Store

  Summon {
    p -> g
    g -> os:  Move current summoned/provider to archive/provider
    g -> os: Populate summoned bucket
    os."The prov bucket is alway empty at this point this approach"
    g -> os: Populate prov bucket
  }

         Load Summoned {
            os -> n: iterate summoned objects 
            n -> ts: prune and load on namespaces
         }

         Build Release Graph {
            os -> n
            n -> os
         }

         Build Release Prov Graph {
            os -> n
            n -> os
         }

         Load Prov {
           n -> ts:  Drop the prov for a provider
           os -> n -> ts:  Load prov from new release prov graph
           os."In this approach only latst prov is present, prov history is in the releases"
         }

         Load Orgs {
            os -> n: iterate summoned objects 
            n -> ts: prune and load on namespaces
         }

}
