API Flow: {
  shape: sequence_diagram
    adm: Administrator

  prt: Portainer
  s3: Minio
  Init: {
        load archive: {
            adm -> s3: load archives
            s3 -> adm: 200
        }
        load orchestration: {
            adm -> prt: load env + compose
        }
    }
    }