version: "3"

services:
  dagster-dagit:
    image: docker.io/fils/dagster_oih:0.0.38
    environment:
    - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    - PORTAINER_URL=${PORTAINER_URL}
    - PORTAINER_KEY=${PORTAINER_KEY}
    - GLEANERIO_GLEANER_IMAGE=${GLEANERIO_GLEANER_IMAGE}
    - GLEANERIO_GLEANER_ARCHIVE_OBJECT=${GLEANERIO_GLEANER_ARCHIVE_OBJECT}
    - GLEANERIO_GLEANER_ARCHIVE_PATH=${GLEANERIO_GLEANER_ARCHIVE_PATH}
    - GLEANERIO_NABU_IMAGE=${GLEANERIO_NABU_IMAGE}
    - GLEANERIO_NABU_ARCHIVE_OBJECT=${GLEANERIO_NABU_ARCHIVE_OBJECT}
    - GLEANERIO_NABU_ARCHIVE_PATH=${GLEANERIO_NABU_ARCHIVE_PATH}
    - GLEANERIO_LOG_PREFIX=${GLEANERIO_LOG_PREFIX}
    - GLEANER_MINIO_URL=${GLEANER_MINIO_URL}
    - GLEANER_MINIO_PORT=${GLEANER_MINIO_PORT}
    - GLEANER_MINIO_SSL=${GLEANER_MINIO_SSL}
    - GLEANER_MINIO_BUCKET=${GLEANER_MINIO_BUCKET}
    - GLEANER_MINIO_KEY=${GLEANER_MINIO_KEY}
    - GLEANER_MINIO_SECRET=${GLEANER_MINIO_SECRET}
    - GLEANER_BASE=${GLEANER_BASE}
    - GLEANER_OBJECTS=${GLEANER_OBJECTS}
    - GLEANER_MEILI=${GLEANER_MEILI}
    - GLEANER_GRAPH=${GLEANER_GRAPH}
    - GLEANER_GRAPH_CONF=${GLEANER_GRAPH_CONF}
    - GLEANER_TRAEFIK=${GLEANER_TRAEFIK}
    - GLEANER_DOMAIN=${GLEANER_DOMAIN}
    - GLEANER_OSS_DOMAIN=${GLEANER_OSS_DOMAIN}
    - GLEANER_GRAPH_DOMAIN=${GLEANER_GRAPH_DOMAIN}
    - GLEANER_WEB_DOMAIN=${GLEANER_WEB_DOMAIN}
    - GLEANER_WEB2_DOMAIN=${GLEANER_WEB2_DOMAIN}
    - GLEANER_INDEX_DOMAIN=${GLEANER_INDEX_DOMAIN}
    - GLEANER_ADMIN_DOMAIN=${GLEANER_ADMIN_DOMAIN}
    ports:
      - 3000:3000
    depends_on:
    - dagster-postgres      
  dagster-daemon:
    image: docker.io/fils/dagster_oih:0.0.38
    environment:
    - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    - PORTAINER_URL=${PORTAINER_URL}
    - PORTAINER_KEY=${PORTAINER_KEY}
    - GLEANERIO_GLEANER_IMAGE=${GLEANERIO_GLEANER_IMAGE}
    - GLEANERIO_GLEANER_ARCHIVE_OBJECT=${GLEANERIO_GLEANER_ARCHIVE_OBJECT}
    - GLEANERIO_GLEANER_ARCHIVE_PATH=${GLEANERIO_GLEANER_ARCHIVE_PATH}
    - GLEANERIO_NABU_IMAGE=${GLEANERIO_NABU_IMAGE}
    - GLEANERIO_NABU_ARCHIVE_OBJECT=${GLEANERIO_NABU_ARCHIVE_OBJECT}
    - GLEANERIO_NABU_ARCHIVE_PATH=${GLEANERIO_NABU_ARCHIVE_PATH}
    - GLEANERIO_LOG_PREFIX=${GLEANERIO_LOG_PREFIX}
    - GLEANER_MINIO_URL=${GLEANER_MINIO_URL}
    - GLEANER_MINIO_PORT=${GLEANER_MINIO_PORT}
    - GLEANER_MINIO_SSL=${GLEANER_MINIO_SSL}
    - GLEANER_MINIO_BUCKET=${GLEANER_MINIO_BUCKET}
    - GLEANER_MINIO_KEY=${GLEANER_MINIO_KEY}
    - GLEANER_MINIO_SECRET=${GLEANER_MINIO_SECRET}
    - GLEANER_BASE=${GLEANER_BASE}
    - GLEANER_OBJECTS=${GLEANER_OBJECTS}
    - GLEANER_MEILI=${GLEANER_MEILI}
    - GLEANER_GRAPH=${GLEANER_GRAPH}
    - GLEANER_GRAPH_CONF=${GLEANER_GRAPH_CONF}
    - GLEANER_TRAEFIK=${GLEANER_TRAEFIK}
    - GLEANER_DOMAIN=${GLEANER_DOMAIN}
    - GLEANER_OSS_DOMAIN=${GLEANER_OSS_DOMAIN}
    - GLEANER_GRAPH_DOMAIN=${GLEANER_GRAPH_DOMAIN}
    - GLEANER_WEB_DOMAIN=${GLEANER_WEB_DOMAIN}
    - GLEANER_WEB2_DOMAIN=${GLEANER_WEB2_DOMAIN}
    - GLEANER_INDEX_DOMAIN=${GLEANER_INDEX_DOMAIN}
    - GLEANER_ADMIN_DOMAIN=${GLEANER_ADMIN_DOMAIN}
    command: "dagster-daemon run"
    depends_on:
    - dagster-postgres    
  dagster-postgres:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=SECRET_HERE
    volumes:
      - dagster-postgres:/var/lib/postgresql/data
volumes:
  dagster-postgres:
    driver: local
