direction: down

gi: Get Image(s) {
    style.fill: "#e0a3ff"
    width: 600
    height: 150
    ex: |python 
    containers = SOURCEVAL_getImage()
    |
}

g: Gleaner Harvest {
    style.fill: honeydew
    width: 600
    height: 150
    ex: |python 
    harvest = SOURCEVAL_gleaner(start=containers)
    |
}

data: Data Graph {
    dr: Build Release Graph {
       style.fill: "#f4a261"
       width: 300
    ex: |python 
    load_release = SOURCEVAL_naburelease(start=harvest)
    |

    }
    udr: Load Release Graph {
       style.fill: "#f4a261"
       width: 300
    ex: |python 
    load_uploadrelease = SOURCEVAL_uploadrelease(start=load_release)
    |
     }

    dp: Prune {
        style.fill: "#f4a261"
        width: 300
    ex: |python 
    load_prune = SOURCEVAL_nabu_prune(start=load_uploadrelease)
    |
    }
}

org: Organization Graph {

    or: Build Release Graph {
        style.fill: "#f4a261"
        width: 300
    ex: |python 
    org_release = SOURCEVAL_nabu_orgsrelease(start=harvest)
    |
    }

   op: Prefix Load Graph {
        style.fill: "#f4a261"
        width: 300
    ex: |python 
    load_org = SOURCEVAL_nabuorgs(start=org_release)
    |
    }

    or -> op

}

prov: Provenance Graph {
    pr: Build Release Graph {
        style.fill: "#f4a261"
        width: 300
    ex: |python 
    prov_release = SOURCEVAL_nabu_provrelease(start=harvest)
    |
    }

    dpg: Clear Current Graph{
        style.fill: "#f4a261"
        width: 300
    ex: |python 
    prov_clear = SOURCEVAL_nabu_provclear(start=prov_release)
    |
    }

   upr:  Load Release Graph {
        style.fill: "#f4a261"
        width: 300
    ex: |python 
    prov_object = SOURCEVAL_nabu_provobject(start=prov_clear)
    |
    }

    dpp: Delete Generated Prov JSON-LD {
        style.fill: "#f4a261"
        width: 300
    ex: |python 
    prov_drain = SOURCEVAL_nabu_provdrain(start=prov_object)
    |
    }
}

r: Reports {
   m: Missing Reports {
        style.fill: "#f4a261"
        width: 300
    ex: |python 
    harvest = SOURCEVAL_gleaner(start=containers)
    |
    }

   id: Identifier stats {
        style.fill: "#f4a261"
        width: 300
    ex: |python 
    harvest = SOURCEVAL_gleaner(start=containers)
    |
    }

   b: Bucket URLs {
        style.fill: "#f4a261"
        width: 300
    ex: |python 
    harvest = SOURCEVAL_gleaner(start=containers)
    |
    }

  m -> id -> b
}

gi -> g
g -> org
g -> data
g -> prov
g -> r

data.dr -> data.udr -> data.dp
prov.pr -> prov.dpg -> prov.upr -> prov.dpp
