from dagster import repository
from jobs.implnet_jobs_obps import implnet_job_obps
from schedules.implnet_sch_obps  import implnet_sch_obps
from jobs.implnet_jobs_edmerp import implnet_job_edmerp
from schedules.implnet_sch_edmerp  import implnet_sch_edmerp
from jobs.implnet_jobs_edmo import implnet_job_edmo
from schedules.implnet_sch_edmo  import implnet_sch_edmo
from jobs.implnet_jobs_invemarexpert import implnet_job_invemarexpert
from schedules.implnet_sch_invemarexpert  import implnet_sch_invemarexpert
from jobs.implnet_jobs_invemardocuments import implnet_job_invemardocuments
from schedules.implnet_sch_invemardocuments  import implnet_sch_invemardocuments
from jobs.implnet_jobs_invemarinstitution import implnet_job_invemarinstitution
from schedules.implnet_sch_invemarinstitution  import implnet_sch_invemarinstitution
from jobs.implnet_jobs_invemarvessel import implnet_job_invemarvessel
from schedules.implnet_sch_invemarvessel  import implnet_sch_invemarvessel
from jobs.implnet_jobs_invemartraining import implnet_job_invemartraining
from schedules.implnet_sch_invemartraining  import implnet_sch_invemartraining
from jobs.implnet_jobs_aquadocs import implnet_job_aquadocs
from schedules.implnet_sch_aquadocs  import implnet_sch_aquadocs
from jobs.implnet_jobs_marinetraining import implnet_job_marinetraining
from schedules.implnet_sch_marinetraining  import implnet_sch_marinetraining
from jobs.implnet_jobs_euroceanprojects import implnet_job_euroceanprojects
from schedules.implnet_sch_euroceanprojects  import implnet_sch_euroceanprojects
from jobs.implnet_jobs_euroceanvessels import implnet_job_euroceanvessels
from schedules.implnet_sch_euroceanvessels  import implnet_sch_euroceanvessels
from jobs.implnet_jobs_euroceanorgs import implnet_job_euroceanorgs
from schedules.implnet_sch_euroceanorgs  import implnet_sch_euroceanorgs
from jobs.implnet_jobs_obis import implnet_job_obis
from schedules.implnet_sch_obis  import implnet_sch_obis
from jobs.implnet_jobs_oceanexperts import implnet_job_oceanexperts
from schedules.implnet_sch_oceanexperts  import implnet_sch_oceanexperts
from jobs.implnet_jobs_euroceanexpert import implnet_job_euroceanexpert
from schedules.implnet_sch_euroceanexpert  import implnet_sch_euroceanexpert
from jobs.implnet_jobs_euroceanevents import implnet_job_euroceanevents
from schedules.implnet_sch_euroceanevents  import implnet_sch_euroceanevents
from jobs.implnet_jobs_euroceantraining import implnet_job_euroceantraining
from schedules.implnet_sch_euroceantraining  import implnet_sch_euroceantraining
 
@repository
def gleaner():
	jobs = [implnet_job_obps,implnet_job_edmerp,implnet_job_edmo,implnet_job_invemarexpert,implnet_job_invemardocuments,implnet_job_invemarinstitution,implnet_job_invemarvessel,implnet_job_invemartraining,implnet_job_aquadocs,implnet_job_marinetraining,implnet_job_euroceanprojects,implnet_job_euroceanvessels,implnet_job_euroceanorgs,implnet_job_obis,implnet_job_oceanexperts,implnet_job_euroceanexpert,implnet_job_euroceanevents,implnet_job_euroceantraining]
	schedules = [implnet_sch_obps,implnet_sch_edmerp,implnet_sch_edmo,implnet_sch_invemarexpert,implnet_sch_invemardocuments,implnet_sch_invemarinstitution,implnet_sch_invemarvessel,implnet_sch_invemartraining,implnet_sch_aquadocs,implnet_sch_marinetraining,implnet_sch_euroceanprojects,implnet_sch_euroceanvessels,implnet_sch_euroceanorgs,implnet_sch_obis,implnet_sch_oceanexperts,implnet_sch_euroceanexpert,implnet_sch_euroceanevents,implnet_sch_euroceantraining]
 
	return jobs + schedules
