minio:
  address: 
  port: 
  accesskey:
  secretkey:
  bucket:
objects:
  domain: us-east-1
  prefix:
  - summoned/reponame
  - prov/reponame
sparql:
  endpoint: http://example.org:3030/oihdev/data
  authenticate: true
  username: admin
  password: password

